create extension if not exists "pgcrypto";

create table if not exists public.bookings (
  id uuid primary key default gen_random_uuid(),
  booking_code text not null unique,
  user_id uuid not null references auth.users (id) on delete cascade,
  customer_name text not null,
  customer_email text,
  phone text not null,
  booking_date date not null,
  booking_time text not null,
  guests integer not null check (guests > 0),
  status text not null default 'Đang chờ',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists bookings_user_id_idx on public.bookings (user_id);
create index if not exists bookings_booking_date_idx on public.bookings (booking_date desc);

alter table public.bookings enable row level security;

drop policy if exists "Users can insert their own bookings" on public.bookings;
drop policy if exists "Users can view their own bookings" on public.bookings;
drop policy if exists "Users can update their own bookings" on public.bookings;

create policy "Users can insert their own bookings"
  on public.bookings
  for insert
  to authenticated
  with check (auth.uid() = user_id);

create policy "Users can view their own bookings"
  on public.bookings
  for select
  to authenticated
  using (auth.uid() = user_id);

create policy "Users can update their own bookings"
  on public.bookings
  for update
  to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create table if not exists public.menu_comments (
  id bigint generated by default as identity primary key,
  name text not null,
  comment_text text not null,
  created_at timestamptz not null default now()
);

alter table public.menu_comments enable row level security;

drop policy if exists "Anyone can view menu comments" on public.menu_comments;
drop policy if exists "Anyone can insert menu comments" on public.menu_comments;

create policy "Anyone can view menu comments"
  on public.menu_comments
  for select
  to anon, authenticated
  using (true);

create policy "Anyone can insert menu comments"
  on public.menu_comments
  for insert
  to anon, authenticated
  with check (true);

create table if not exists public.contact_requests (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  message text not null,
  created_at timestamptz not null default now()
);

alter table public.contact_requests enable row level security;

drop policy if exists "Anyone can insert contact requests" on public.contact_requests;
drop policy if exists "Authenticated users can view contact requests" on public.contact_requests;

create policy "Anyone can insert contact requests"
  on public.contact_requests
  for insert
  to anon, authenticated
  with check (true);

create policy "Authenticated users can view contact requests"
  on public.contact_requests
  for select
  to authenticated
  using (true);
