create table if not exists public.admin_users (
  email text primary key,
  role text not null default 'admin',
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

insert into public.admin_users (email, role, is_active)
values ('ducanh12082007dn@gmail.com', 'admin', true)
on conflict (email) do update
set role = excluded.role,
    is_active = excluded.is_active;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.admin_users a
    where a.email = lower(auth.jwt() ->> 'email')
      and a.is_active = true
  );
$$;

alter table public.bookings
  add column if not exists deposit_amount integer not null default 20000,
  add column if not exists payment_code text unique,
  add column if not exists payment_status text not null default 'Chờ thanh toán',
  add column if not exists payment_expires_at timestamptz,
  add column if not exists payment_confirmed_at timestamptz,
  add column if not exists admin_note text,
  add column if not exists admin_updated_at timestamptz,
  add column if not exists admin_updated_by uuid;

create table if not exists public.payments (
  id uuid primary key default gen_random_uuid(),
  booking_id uuid not null references public.bookings (id) on delete cascade,
  booking_code text not null,
  payment_code text not null unique,
  provider text not null default 'sepay',
  status text not null default 'Chờ thanh toán',
  amount integer not null default 100000 check (amount > 0),
  currency text not null default 'VND',
  bank_code text,
  bank_account text,
  bank_account_name text,
  qr_url text,
  provider_transaction_id text,
  transfer_amount integer,
  transfer_content text,
  raw_payload jsonb,
  paid_at timestamptz,
  expires_at timestamptz not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.payment_webhook_events (
  id bigint generated by default as identity primary key,
  provider text not null default 'sepay',
  provider_transaction_id text,
  payment_code text,
  status text not null default 'received',
  raw_payload jsonb not null,
  received_at timestamptz not null default now(),
  processed_at timestamptz,
  error_message text
);

create unique index if not exists payments_provider_transaction_id_idx
  on public.payments (provider, provider_transaction_id)
  where provider_transaction_id is not null;

create index if not exists payments_booking_id_idx on public.payments (booking_id);
create index if not exists payments_status_idx on public.payments (status);
create index if not exists bookings_payment_code_idx on public.bookings (payment_code);
create index if not exists bookings_payment_status_idx on public.bookings (payment_status);

drop index if exists public.bookings_active_slot_idx;

create unique index if not exists bookings_active_slot_idx
  on public.bookings (booking_date, booking_time)
  where status not in ('Đã hủy - mất cọc', 'Hết hạn thanh toán');

create or replace function public.get_booked_slots(target_date date)
returns table (booking_time text)
language sql
security definer
set search_path = public
as $$
  select distinct b.booking_time
  from public.bookings b
  where b.booking_date = target_date
    and b.status not in ('Đã hủy - mất cọc', 'Hết hạn thanh toán')
    and (
      b.payment_expires_at is null
      or b.payment_expires_at > now()
      or b.payment_status = 'Đã nhận tiền'
    )
  order by b.booking_time;
$$;

revoke all on function public.get_booked_slots(date) from public;
grant execute on function public.get_booked_slots(date) to anon, authenticated;

alter table public.payments enable row level security;
alter table public.payment_webhook_events enable row level security;
alter table public.admin_users enable row level security;

drop policy if exists "Admins can view admin users" on public.admin_users;
create policy "Admins can view admin users"
  on public.admin_users
  for select
  to authenticated
  using (public.is_admin());

drop policy if exists "Users can view their own payments" on public.payments;
drop policy if exists "Admins can view all payments" on public.payments;

create policy "Users can view their own payments"
  on public.payments
  for select
  to authenticated
  using (
    exists (
      select 1
      from public.bookings b
      where b.id = payments.booking_id
        and b.user_id = auth.uid()
    )
  );

create policy "Admins can view all payments"
  on public.payments
  for select
  to authenticated
  using (public.is_admin());

drop policy if exists "Admins can view payment webhook events" on public.payment_webhook_events;

create policy "Admins can view payment webhook events"
  on public.payment_webhook_events
  for select
  to authenticated
  using (public.is_admin());

drop policy if exists "Admin can view all bookings" on public.bookings;
drop policy if exists "Admin can update all bookings" on public.bookings;
drop policy if exists "Admin can delete bookings" on public.bookings;
drop policy if exists "Users can update their own bookings" on public.bookings;
drop policy if exists "Users can insert their own bookings" on public.bookings;

create policy "Admin can view all bookings"
  on public.bookings
  for select
  to authenticated
  using (public.is_admin());

create policy "Admin can update all bookings"
  on public.bookings
  for update
  to authenticated
  using (public.is_admin())
  with check (public.is_admin());

create policy "Admin can delete bookings"
  on public.bookings
  for delete
  to authenticated
  using (public.is_admin());

drop policy if exists "Admin can view contact requests" on public.contact_requests;
drop policy if exists "Admin can update contact requests" on public.contact_requests;
create policy "Admin can view contact requests"
  on public.contact_requests
  for select
  to authenticated
  using (public.is_admin());

create policy "Admin can update contact requests"
  on public.contact_requests
  for update
  to authenticated
  using (public.is_admin())
  with check (public.is_admin());

alter table public.contact_requests
  add column if not exists status text not null default 'Mới',
  add column if not exists reply_note text,
  add column if not exists replied_at timestamptz,
  add column if not exists replied_by uuid;

create table if not exists public.newsletter_subscribers (
  id bigint generated by default as identity primary key,
  email text not null unique,
  source text not null default 'footer',
  status text not null default 'active',
  created_at timestamptz not null default now()
);

alter table public.newsletter_subscribers enable row level security;

drop policy if exists "Anyone can subscribe newsletter" on public.newsletter_subscribers;
drop policy if exists "Admins can view newsletter subscribers" on public.newsletter_subscribers;

create policy "Anyone can subscribe newsletter"
  on public.newsletter_subscribers
  for insert
  to anon, authenticated
  with check (true);

create policy "Admins can view newsletter subscribers"
  on public.newsletter_subscribers
  for select
  to authenticated
  using (public.is_admin());
