create table if not exists public.menu_items (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null,
  price integer not null check (price >= 0),
  description text not null default '',
  image_url text not null default '',
  is_available boolean not null default true,
  is_active boolean not null default true,
  is_popular boolean not null default false,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists menu_items_name_key on public.menu_items (lower(name));
create index if not exists menu_items_category_idx on public.menu_items (category);
create index if not exists menu_items_sort_order_idx on public.menu_items (sort_order, id);

alter table public.menu_items enable row level security;

drop policy if exists "Anyone can view active menu items" on public.menu_items;
drop policy if exists "Admin can insert menu items" on public.menu_items;
drop policy if exists "Admin can update menu items" on public.menu_items;

create policy "Anyone can view active menu items"
  on public.menu_items
  for select
  to anon, authenticated
  using (is_active = true);

create policy "Admin can insert menu items"
  on public.menu_items
  for insert
  to authenticated
  with check (lower(auth.jwt() ->> 'email') = 'ducanh12082007dn@gmail.com');

create policy "Admin can update menu items"
  on public.menu_items
  for update
  to authenticated
  using (lower(auth.jwt() ->> 'email') = 'ducanh12082007dn@gmail.com')
  with check (lower(auth.jwt() ->> 'email') = 'ducanh12082007dn@gmail.com');

insert into public.menu_items (
  name,
  category,
  price,
  description,
  image_url,
  is_available,
  is_active,
  is_popular,
  sort_order
)
values
  ('Sườn Bò Wagyu Nướng Than', 'bo', 520000, 'Sườn bò vân mỡ đẹp, nướng than thơm khói nhẹ. Hợp ăn cùng muối tiêu và rau cuốn.', 'https://images.unsplash.com/photo-1544025162-d76694265947?q=80&w=1200&auto=format&fit=crop', true, true, true, 1),
  ('Ba Chỉ Heo Sốt Gochujang', 'heo', 280000, 'Ba chỉ heo mềm béo, ướp sốt gochujang cay ngọt. Nướng xém cạnh ăn rất bắt vị.', 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?q=80&w=1200&auto=format&fit=crop', true, true, false, 2),
  ('Tôm Càng Nướng Bơ Tỏi', 'hai-san', 360000, 'Tôm càng chắc thịt, phủ bơ tỏi thơm béo. Vị ngọt hải sản nổi rõ sau khi nướng.', 'https://images.unsplash.com/photo-1565299507177-b0ac66763828?q=80&w=1200&auto=format&fit=crop', true, true, false, 3),
  ('Set Ember Signature', 'combo', 890000, 'Set tổng hợp thịt nướng đặc trưng của Ember. Phù hợp cho nhóm muốn thử nhiều vị.', 'https://images.unsplash.com/photo-1525755662778-989d0524087e?q=80&w=1200&auto=format&fit=crop', true, true, true, 4),
  ('Dẻ Sườn Bò Mỹ Sốt Tiêu Đen', 'bo', 430000, 'Dẻ sườn bò Mỹ mọng nước, sốt tiêu đen cay ấm. Miếng thịt đậm vị và dễ ăn.', 'https://images.unsplash.com/photo-1546964124-0cce460f38ef?q=80&w=1200&auto=format&fit=crop', true, true, false, 5),
  ('Lõi Vai Bò Nướng Miso', 'bo', 390000, 'Lõi vai bò mềm, ướp miso mặn ngọt kiểu Nhật. Nướng vừa chín để giữ độ mọng.', 'https://images.unsplash.com/photo-1600891964092-4316c288032e?q=80&w=1200&auto=format&fit=crop', true, true, true, 6),
  ('Nạc Vai Heo Iberico Nướng', 'heo', 340000, 'Nạc vai heo Iberico có độ béo nhẹ và thơm. Hợp chấm sốt mè hoặc muối ớt xanh.', 'https://images.unsplash.com/photo-1603360946369-dc9bb6258143?q=80&w=1200&auto=format&fit=crop', true, true, false, 7),
  ('Sườn Non Heo Sốt Mật Ong', 'heo', 315000, 'Sườn non ướp mật ong dịu ngọt, nướng lên bóng màu. Phần thịt mềm, thơm khói.', 'https://images.unsplash.com/photo-1558030006-450675393462?q=80&w=1200&auto=format&fit=crop', true, true, false, 8),
  ('Gà Rút Xương Sốt Cay Hàn', 'ga', 265000, 'Gà rút xương ướp sốt cay Hàn Quốc. Thịt mềm, vị cay vừa đủ để ăn cùng cơm nóng.', 'https://images.unsplash.com/photo-1527477396000-e27163b481c2?q=80&w=1200&auto=format&fit=crop', true, true, false, 9),
  ('Đùi Gà Nướng Thảo Mộc', 'ga', 245000, 'Đùi gà ướp thảo mộc, thơm nhẹ và ít cay. Phần da nướng vàng, bên trong vẫn mọng.', 'https://images.unsplash.com/photo-1608039755401-742074f0548d?q=80&w=1200&auto=format&fit=crop', true, true, false, 10),
  ('Mực Lá Nướng Muối Ớt', 'hai-san', 295000, 'Mực lá tươi giòn, nướng muối ớt dậy mùi. Vị cay mặn rõ, hợp uống kèm đồ lạnh.', 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?q=80&w=1200&auto=format&fit=crop', true, true, false, 11),
  ('Rau Củ Nướng Sốt Mè', 'rau', 160000, 'Rau củ theo mùa nướng nhẹ để giữ độ ngọt. Sốt mè rang béo thơm, cân bằng bữa nướng.', 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?q=80&w=1200&auto=format&fit=crop', true, true, false, 12),
  ('Combo Hải Sản Hoàng Kim', 'combo', 990000, 'Combo hải sản nhiều loại, có tôm, mực và món vỏ. Dành cho bàn thích vị biển rõ ràng.', 'https://images.unsplash.com/photo-1559847844-5315695dadae?q=80&w=1200&auto=format&fit=crop', true, true, true, 13),
  ('Combo Premium 2 Người', 'combo', 1150000, 'Set cao cấp cho 2 người với thịt và hải sản chọn lọc. Khẩu phần gọn nhưng đủ vị.', 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&q=80&w=1200', true, true, false, 14),
  ('Khoai Tây Chiên Bơ Tỏi', 'rau', 95000, 'Khoai chiên giòn ngoài mềm trong, áo bơ tỏi thơm. Món ăn kèm dễ hợp mọi bàn.', 'https://images.unsplash.com/photo-1576107232684-1279f390859f?q=80&w=1200&auto=format&fit=crop', true, true, false, 15),
  ('Khoai Tây Chiên Lắc Phô Mai', 'rau', 109000, 'Khoai chiên nóng phủ bột phô mai mặn ngọt. Vị béo nhẹ, hợp gọi thêm cho trẻ em.', 'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?q=80&w=1200&auto=format&fit=crop', true, true, false, 16),
  ('Khoai Tây Múi Cau Nướng Thảo Mộc', 'rau', 119000, 'Khoai múi cau nướng cùng thảo mộc và dầu olive. Vị bùi, thơm, không quá ngấy.', 'https://images.unsplash.com/photo-1630384060421-cb20d0e0649d?q=80&w=1200&auto=format&fit=crop', true, true, false, 17),
  ('Hàu Nhật Nướng Phô Mai', 'hai-san', 325000, 'Hàu béo phủ phô mai tan chảy, nướng thơm mặt. Vị mặn ngọt tự nhiên và béo nhẹ.', 'https://images.unsplash.com/photo-1717251883201-675b5ee5b1a6?q=80&w=1200&auto=format&fit=crop', true, true, false, 18),
  ('Sò Điệp Hokkaido Nướng Bơ Tỏi', 'hai-san', 420000, 'Sò điệp dày thịt, nướng cùng bơ tỏi thơm nồng. Ăn nóng để cảm rõ vị ngọt.', 'https://images.unsplash.com/photo-1761314037182-8ea3363cf3a3?q=80&w=1200&auto=format&fit=crop', true, true, false, 19),
  ('Bạch Tuộc Nướng Sa Tế', 'hai-san', 385000, 'Bạch tuộc giòn sần sật, ướp sa tế cay thơm. Lên than cho cạnh xém và mùi khói rõ.', 'https://images.unsplash.com/photo-1764397514747-8272f2da3f36?q=80&w=1200&auto=format&fit=crop', true, true, false, 20),
  ('Cá Hồi Na Uy Áp Than', 'hai-san', 455000, 'Cá hồi Na Uy béo mềm, áp than nhẹ cho thơm vỏ. Phần thịt giữ độ ẩm và vị ngọt.', 'https://images.unsplash.com/photo-1747097950921-6e273f14b47f?q=80&w=1200&auto=format&fit=crop', true, true, false, 21),
  ('Cua Lột Nướng Muối Ớt', 'hai-san', 510000, 'Cua lột nướng muối ớt, vỏ mềm và thịt ngọt. Vị cay mặn làm nổi độ béo của cua.', 'https://images.unsplash.com/photo-1655992829046-ae2d44d205f7?q=80&w=1200&auto=format&fit=crop', true, true, false, 22),
  ('Nghêu Nướng Mỡ Hành', 'hai-san', 235000, 'Nghêu nướng mỡ hành thơm béo, rắc thêm đậu phộng. Món nhẹ, hợp khai vị bàn nướng.', 'https://images.unsplash.com/photo-1759337677690-ef7608ce9e5b?q=80&w=1200&auto=format&fit=crop', true, true, false, 23),
  ('Tôm Sú Xiên Que Sốt Cay', 'hai-san', 340000, 'Tôm sú xiên que nướng than, áo sốt cay đậm. Thịt tôm chắc, thơm khói và dễ chia.', 'https://images.unsplash.com/photo-1601899982456-2555673f3707?q=80&w=1200&auto=format&fit=crop', true, true, false, 24),
  ('Trà Lúa Mạch Lạnh', 'do-uong', 45000, 'Vị rang thơm nhẹ, hậu vị thanh. Uống lạnh giúp cân bằng vị béo của BBQ.', 'https://images.unsplash.com/photo-1544145945-f90425340c7e?q=80&w=1200&auto=format&fit=crop', true, true, false, 25),
  ('Soda Chanh Sả', 'do-uong', 55000, 'Soda chanh tươi cùng hương sả mát. Vị chua dịu, gas nhẹ và rất giải ngấy.', 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?q=80&w=1200&auto=format&fit=crop', true, true, false, 26),
  ('Nước Ép Dứa Bạc Hà', 'do-uong', 65000, 'Dứa ép chua ngọt tự nhiên, thêm bạc hà mát. Hợp dùng giữa bữa nướng nhiều thịt.', 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?q=80&w=1200&auto=format&fit=crop', true, true, false, 27),
  ('Mojito Không Cồn', 'do-uong', 78000, 'Chanh, bạc hà và soda tạo vị mát rõ. Không cồn, dễ uống cho mọi nhóm khách.', 'https://images.unsplash.com/photo-1461823385004-d7660947a7c0?q=80&w=1200&auto=format&fit=crop', true, true, false, 28),
  ('Nước Ép Cam Gừng', 'do-uong', 72000, 'Cam tươi ngọt dịu kết hợp gừng ấm. Vị thơm sắc, giúp bữa ăn bớt nặng.', 'https://images.unsplash.com/photo-1497534446932-c925b458314e?q=80&w=1200&auto=format&fit=crop', true, true, false, 29),
  ('Trà Đào Kem Cheese', 'do-uong', 69000, 'Trà đào thơm, lớp kem cheese béo mặn nhẹ. Vị ngọt vừa, hợp uống sau món cay.', 'https://images.pexels.com/photos/33573170/pexels-photo-33573170.jpeg?cs=srgb&dl=pexels-soc-nang-d-ng-2150345854-33573170.jpg&fm=jpg', true, true, false, 30),
  ('Soda Dâu Tươi', 'do-uong', 59000, 'Dâu tươi chua ngọt cùng nền soda mát. Màu đẹp, vị nhẹ và dễ uống.', 'https://images.pexels.com/photos/6574739/pexels-photo-6574739.jpeg?cs=srgb&dl=pexels-roman-odintsov-6574739.jpg&fm=jpg', true, true, false, 31),
  ('Matcha Latte Đá', 'do-uong', 76000, 'Matcha thơm đậm, sữa lạnh béo mịn. Hậu vị trà xanh nhẹ, không quá ngọt.', 'https://images.unsplash.com/photo-1515823064-d6e0c04616a7?q=80&w=1200&auto=format&fit=crop', true, true, false, 32),
  ('Nước Ép Ổi Hồng', 'do-uong', 63000, 'Ổi hồng ép tươi có vị thanh và thơm dịu. Phù hợp khi muốn đồ uống ít béo.', 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?q=80&w=1200&auto=format&fit=crop', true, true, false, 33),
  ('Cold Brew Cam', 'do-uong', 81000, 'Cold brew đậm nhẹ hòa cùng cam tươi. Vị đắng thanh, chua ngọt cân bằng.', 'https://images.unsplash.com/photo-1461023058943-07fcbe16d735?q=80&w=1200&auto=format&fit=crop', true, true, false, 34),
  ('Sữa Chua Việt Quất', 'do-uong', 68000, 'Sữa chua mịn kết hợp việt quất chua ngọt. Vị mát, hợp dùng cuối bữa.', 'https://images.unsplash.com/photo-1488477181946-6428a0291777?q=80&w=1200&auto=format&fit=crop', true, true, false, 35),
  ('Trà Gừng Mật Ong', 'do-uong', 52000, 'Trà gừng ấm nhẹ với mật ong thơm dịu. Có thể uống nóng hoặc lạnh tùy khẩu vị.', 'https://images.unsplash.com/photo-1610450622827-195cb7308af8?q=80&w=1200&auto=format&fit=crop', true, true, false, 36)
on conflict ((lower(name))) do update set
  category = excluded.category,
  price = excluded.price,
  description = excluded.description,
  image_url = excluded.image_url,
  is_active = true,
  is_popular = excluded.is_popular,
  sort_order = excluded.sort_order,
  updated_at = now();

insert into storage.buckets (id, name, public)
values ('menu-images', 'menu-images', true)
on conflict (id) do update set public = true;

drop policy if exists "Anyone can view menu images" on storage.objects;
drop policy if exists "Admin can upload menu images" on storage.objects;
drop policy if exists "Admin can update menu images" on storage.objects;

create policy "Anyone can view menu images"
  on storage.objects
  for select
  to anon, authenticated
  using (bucket_id = 'menu-images');

create policy "Admin can upload menu images"
  on storage.objects
  for insert
  to authenticated
  with check (
    bucket_id = 'menu-images'
    and lower(auth.jwt() ->> 'email') = 'ducanh12082007dn@gmail.com'
  );

create policy "Admin can update menu images"
  on storage.objects
  for update
  to authenticated
  using (
    bucket_id = 'menu-images'
    and lower(auth.jwt() ->> 'email') = 'ducanh12082007dn@gmail.com'
  )
  with check (
    bucket_id = 'menu-images'
    and lower(auth.jwt() ->> 'email') = 'ducanh12082007dn@gmail.com'
  );
